version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  init-db:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: caffeino_local_django
    container_name: django_caffeino
    depends_on:
      - postgres
      - mongo
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.mongodb
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: caffeino_production_postgres
    container_name: postgres_caffeino
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init-db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    env_file:
      - ./.envs/.local/.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.envs/.local/.mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  docs:
    image: caffeino_local_docs
    container_name: docs_caffeino
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./caffeino:/app/caffeino:z
    ports:
      - "7000:7000"
