db.machines.insertMany([
    {sku: 'CM001', product_type: 'COFFEE_MACHINE_SMALL', water_line_compatible: 'false'},
    {sku: 'CM002', product_type: 'COFFEE_MACHINE_SMALL', water_line_compatible: 'false'},
    {sku: 'CM003', product_type: 'COFFEE_MACHINE_SMALL', water_line_compatible: 'true'},
    {sku: 'CM101', product_type: 'COFFEE_MACHINE_LARGE', water_line_compatible: 'false'},
    {sku: 'CM102', product_type: 'COFFEE_MACHINE_LARGE', water_line_compatible: 'true'},
    {sku: 'CM103', product_type: 'COFFEE_MACHINE_LARGE', water_line_compatible: 'true'},
    {sku: 'EM001', product_type: 'ESPRESSO_MACHINE', water_line_compatible: 'false'},
    {sku: 'EM002', product_type: 'ESPRESSO_MACHINE', water_line_compatible: 'false'},
    {sku: 'EM003', product_type: 'ESPRESSO_MACHINE', water_line_compatible: 'true'}
]);

db.pods.insertMany([
    {sku: 'CP001', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_VANILLA', pack_size: '12'},
    {sku: 'CP003', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_VANILLA', pack_size: '36'},
    {sku: 'CP011', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_CARAMEL', pack_size: '12'},
    {sku: 'CP013', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_CARAMEL', pack_size: '36'},
    {sku: 'CP021', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_PSL', pack_size: '12'},
    {sku: 'CP023', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_PSL', pack_size: '36'},
    {sku: 'CP031', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_MOCHA', pack_size: '12'},
    {sku: 'CP033', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_MOCHA', pack_size: '36'},
    {sku: 'CP041', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT', pack_size: '12'},
    {sku: 'CP043', product_type: 'COFFEE_POD_SMALL', coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT', pack_size: '36'},
    {sku: 'CP101', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_VANILLA', pack_size: '12'},
    {sku: 'CP103', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_VANILLA', pack_size: '36'},
    {sku: 'CP111', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_CARAMEL', pack_size: '12'},
    {sku: 'CP113', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_CARAMEL', pack_size: '36'},
    {sku: 'CP121', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_PSL', pack_size: '12'},
    {sku: 'CP123', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_PSL', pack_size: '36'},
    {sku: 'CP131', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_MOCHA', pack_size: '12'},
    {sku: 'CP133', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_MOCHA', pack_size: '36'},
    {sku: 'CP141', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT', pack_size: '12'},
    {sku: 'CP143', product_type: 'COFFEE_POD_LARGE', coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT', pack_size: '36'},
    {sku: 'EP003', product_type: 'ESPRESSO_POD', coffee_flavor: 'COFFEE_FLAVOR_VANILLA', pack_size: '36'},
    {sku: 'EP005', product_type: 'ESPRESSO_POD', coffee_flavor: 'COFFEE_FLAVOR_VANILLA', pack_size: '60'},
    {sku: 'EP007', product_type: 'ESPRESSO_POD', coffee_flavor: 'COFFEE_FLAVOR_VANILLA', pack_size: '84'},
    {sku: 'EP013', product_type: 'ESPRESSO_POD', coffee_flavor: 'COFFEE_FLAVOR_CARAMEL', pack_size: '36'},
    {sku: 'EP015', product_type: 'ESPRESSO_POD', coffee_flavor: 'COFFEE_FLAVOR_CARAMEL', pack_size: '60'},
    {sku: 'EP017', product_type: 'ESPRESSO_POD', coffee_flavor: 'COFFEE_FLAVOR_CARAMEL', pack_size: '84'},
]);
